### PR TITLE
Fix typo in RecommendedInstanceProbabilityFilter.java

### PR DESCRIPTION
**Pull request by menof36go**
I think this might be a simple typo mistake

### CODE REVIEW

**Review by dfuchss — APPROVED** [review]
Indeed. Thanks a lot.
I'll run the CI and if it's green the PR can be merged 👍

**Review by dfuchss — CHANGES_REQUESTED** [review]
Ok .. CI says that this decreases the performance. Therefore, it may be the case that this is just bad naming but the actual task was on purpose. We'll have a look at it.

**Comment by menof36go** [comment]
> Ok .. CI says that this decreases the performance. Therefore, it may be the case that this is just bad naming but the actual task was on purpose. We'll have a look at it.

Yes, i noticed that as well. In some cases it greatly reduces the results for MME-Inconsistency detection. Im really confused whether or not this is intended, but it seems unlikely to me

**Comment by dfuchss** [comment]
We figured out that the naming could be better but the code is intended. We'll fix the naming and documentation in the future.

**Pull request closed without merging**
