### PR TITLE
Add tests for InstanceRelation

### PR DESCRIPTION
**Pull request by maGitty**

### CODE REVIEW

**Comment by maGitty** [comment]
Not sure about those failures, looks like they are coming from InconsistencyIT, PipelineIT and TracelinksIT, but I just applied changes to my own tests with minor changes to InstanceRelation and the implemented Interface which is not used elsewhere. Maybe this issue is already known?

**Comment by Gram21** [comment]
The main branch builds and runs smoothly. I cannot tell, yet, why this is not the case for this PR. I will check and report back

**Comment by maGitty** [comment]
> The main branch builds and runs smoothly. I cannot tell, yet, why this is not the case for this PR. I will check and report back

Thanks a lot @Gram21

**Comment by Gram21** [comment]
The build actually also fails locally. After some checks, I realized where the error is: You created a package `edu.kit.kastel.mcse.ardoco.core.recommendationgenerator` for your tests within the test-module. This hides the original package that is needed by the other tests to load certain classes, thus fails these tests. This is fixed in commit f65ba6ab533fdf5779c595fcee43471ba424cb73

**Pull request merged**
